apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rwx-test
  labels:
    app: rwx-test
spec:
  selector:
    matchLabels:
      app: rwx-test
  template:
    metadata:
      labels:
        app: rwx-test
    spec:
      containers:
      - name: logger
        image: alpine
        command: ['sh', '-c', 'while true; do echo hello from $(hostname) at $(date) | tee -a /log/log-$(hostname).log; sleep 30; done']
        volumeMounts:
        - name: log
          mountPath: /log/
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: rwx-test-pvc
