#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-test-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: #@ data.values.storageClass
